### ISSUE TITLE
[nodecode] persist stats between node restarts

### ISSUE THREAD

**Issue by huglester** [VeriBlock/nodecore-releases#107]
Hello,

while it is not importand to persist those stats (ROUNDS), it would be good to have them.
with 0.2.14 those were keeping between restart.

But with 0.2.17 - for me it got stuck. Needed to kill the nodecode (kill -9), start it.
After this - stats were gone.

Thank you

**Comment by timstall** [comment]
Pool stats should be persisted to a file in the testnet directory. If nodecore is restarted, the pool stats should persist. (if a fresh install with a new testnet folder, then pool stats will be reset)

**Comment by JoshRack** [comment]
Fixed in v0.3.4
