### ISSUE TITLE
[POP miner] miner is freezed

### ISSUE THREAD

**Issue by whatwillibe** [VeriBlock/nodecore-releases#108]
[veriblock.nodecore-pop.2018-09-12.0.log](https://github.com/VeriBlock/nodecore-releases/files/2380076/veriblock.nodecore-pop.2018-09-12.0.log)
[veriblock.nodecore-pop.log](https://github.com/VeriBlock/nodecore-releases/files/2380077/veriblock.nodecore-pop.log)
[bitcoinj.nodecore-pop.2018-09-11.0.log](https://github.com/VeriBlock/nodecore-releases/files/2380078/bitcoinj.nodecore-pop.2018-09-11.0.log)
[bitcoinj.nodecore-pop.2018-09-12.0.log](https://github.com/VeriBlock/nodecore-releases/files/2380079/bitcoinj.nodecore-pop.2018-09-12.0.log)
[bitcoinj.nodecore-pop.2018-09-12.1.log](https://github.com/VeriBlock/nodecore-releases/files/2380080/bitcoinj.nodecore-pop.2018-09-12.1.log)
[bitcoinj.nodecore-pop.2018-09-12.2.log](https://github.com/VeriBlock/nodecore-releases/files/2380081/bitcoinj.nodecore-pop.2018-09-12.2.log)
[Uploading bitcoinj.nodecore-pop.2018-09-12.3.log…]()
[Uploading bitcoinj.nodecore-pop.2018-09-12.4.log…]()
[Uploading bitcoinj.nodecore-pop.log…]()
[Uploading veriblock.nodecore-pop.2018-09-11.0.log…]()
[Uploading veriblock.nodecore-pop.2018-09-11.1.log…]()

I somtimes have got this problem. 
when I get this problem, I have to delete  bitcoin-pop-testnet.wallet file.
plz look into these log file

**Comment by JoshRack** [comment]
v0.3.4 released on October 1 included a number of changes to how an operation flowed through it's different stages including releasing resources during some of the long wait periods. We believe these changes fixed this issue.
