### ISSUE TITLE
Pool html page has symbols in non-english languages

### ISSUE THREAD

**Issue by timstall** [VeriBlock/nodecore-releases#110]
![image](https://user-images.githubusercontent.com/9978739/47186903-b62da580-d2f7-11e8-8641-560e18de7956.png)

**Comment by timstall** [comment]
screenshot from a community member, machine language = Russian

**Comment by huglester** [comment]
Ithink it was fixed, no?

**Comment by Shekelme** [comment]
The same thing youy can see at my pool: [http://37.194.10.30:8500/](url)

**Comment by BernatCarbo** [comment]
The whole pool engine was updated some time ago, this issue should be resolved by now.

**Comment by Shekelme** [comment]
It's good when problems are solved by themselves, right?
