### ISSUE TITLE
Rename 'viewrecentrewards' in nodecore-pop for uniformity

### ISSUE THREAD

**Issue by ghost** [VeriBlock/nodecore-releases#113]
Some of the current pop miner commands begin with "show" and one begins with "view"-

```
 showbitcoinaddress
 showbitcoinbalance
 showmineraddress
 showrecentbitcoinfees
 viewrecentrewards
```

I consistently get these mixed up, as 'show' and 'view' appear to mean the same thing (ex. 'viewbitcoinbalance').  I'd suggest renaming 'viewrecentrewards' to 'showrecentrewards' unless there was a specific reason for doing that that I'm unaware of.

**Comment by Leonardiae** [comment]
I would like to support this issue but propose not to rename the command but add an alias. That way both commands work.

**Comment by BernatCarbo** [comment]
We added 'showrecentrewards' alias to the 'viewrecentrewards' command for the next release.
Ref: https://github.com/VeriBlock/nodecore/commit/4c871331c2195d174ba9100ecaabe8a8d5f3647b
