### ISSUE TITLE
[Feature Request][PoP Miner] Standard number of significant digits needed in pop miner btc wallet balance

### ISSUE THREAD

**Issue by sketron1** [VeriBlock/nodecore-releases#115]
Currently the pop miner btc wallet truncates the decimal places when showing the bitcoin balance.  Will be much more convenient if the btc wallet balance is always shown with 8 digits to the right of the decimal place.  e.g. 1,250 sats should always be shown as 0.00001250 instead of being truncated to 0.0000125

**Comment by BernatCarbo** [comment]
This was implemented long ago, closed.
