### ISSUE TITLE
Where is RPC spec?

### ISSUE THREAD

**Issue by pigfrown** [VeriBlock/nodecore-releases#117]
Is there a specification for the RPC commands? 

Since there is no source code for nodecore and no RPC specification it makes it hard to develop on this coin. A JVM dependency is not always an option.

When will:

a) the source code be released, so developers can build their own RPC clients?

b) failing that, an RPC spec be released, so developers can build their own RPC clients?

**Comment by timstall** [comment]
here: https://wiki.veriblock.org/index.php?title=GRPC

Also details here: https://wiki.veriblock.org/index.php?title=Developer_Guide

RPC clients are very welcome.
