### ISSUE TITLE
white list

### ISSUE THREAD

**Issue by prettyCoders** [VeriBlock/nodecore-releases#122]
How to set the Nodecore white list?

**Comment by prettyCoders** [comment]
？？？？？？？？anybody there

**Comment by Leonardiae** [comment]
Source: https://wiki.veriblock.org/index.php?title=NodeCore_Networking#IP_Whitelisting

IP Whitelisting
For a NodeCore instance, IP Whitelisting allows explicitly adding IPs such that only remote clients on that list can connect to your VeriBlock NodeCore instance.

1. In nodecore.properties, change the admin endpoint to bind to 0.0.0.0 and add a whitelist entry for your IP address.

Note that NodeCore expects IPv4, such as: http://whatismyip.host

#no longer directly bound to local host
rpc.bind.address=0.0.0.0

#allow the specified IP to connect
rpc.whitelist.addresses = 98.213.111.91
Note that the whitelist entry is a CSV list. It can be a:

single IP address, e.g. 192.168.1.1
"wildcard" IP, e.g. 192.168.*.* (which would be all IP's in the 192.168 range)
CIDR representation, e.g. 192.168.0.0/16
2. If there is a firewall between the VeriBlock NodeCore instance and the device(s) you wish to allow access to, then open port 10500.

This will vary depending on your operating system. Here is an example for a RHEL-based linux distro (example is CentOS 7):

firewall-cmd --permanent --add-port=10500/tcp
firewall-cmd --reload
3. Restart NodeCore.
