### ISSUE TITLE
Invalid maximum heap size: -Xmx6g

### ISSUE THREAD

**Issue by ArtRaptors** [VeriBlock/nodecore-releases#128]
When I run C:\veriblock-nodecore-all-0.4.6\nodecore-0.4.6\bin\nodecore.bat
I am receiving this text in CLI:
> Invalid maximum heap size: -Xmx6g
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Application terminated unexpectedly, press any key to exit
> 
How to solve this issue and run nodecore and wallet cli?

**Comment by Leonardiae** [comment]
In most cases the causes is that not Java 64 bits is installed or else there is not enough memory.

**Comment by ArtRaptors** [comment]
True. Java was not x64. Thanks
