### ISSUE TITLE
Ask the developer for help. The block synchronization stuck has been in 715763/761954 for two days. Please leave email details.

### ISSUE THREAD

**Issue by xjqxzyr** [VeriBlock/nodecore-releases#129]
![f9a28a4208164a7bdeed34e5c361a82](https://user-images.githubusercontent.com/5488333/71638029-9c277b00-2c8f-11ea-96e0-cfd0f215046d.jpg)

**Comment by dimitryB** [comment]
hit Enter in the console window...

**Comment by xjqxzyr** [comment]
I'll try it first, can you tell me the reason for the jam?

**Comment by xjqxzyr** [comment]
![1577859356(1)](https://user-images.githubusercontent.com/5488333/71638681-8a4ed380-2ca1-11ea-809e-760410dc89fc.png)

The screen scrolls, but the data of the block synchronization has not changed

**Comment by xjqxzyr** [comment]
![c747726125349ea2011db7e18d41b08](https://user-images.githubusercontent.com/5488333/71638693-fd584a00-2ca1-11ea-8a08-d871dd347e34.jpg)
![485084fec3a12c9f698fc8ace96211c](https://user-images.githubusercontent.com/5488333/71638694-fe897700-2ca1-11ea-977c-65b2d8085fcf.jpg)

**Comment by xjqxzyr** [comment]
The network connection failed. Is there any way to complete the synchronization? I have downloaded a complete bootstrap file, 50G

**Comment by Leonardiae** [comment]
Did you try closing Nodecore and starting it again?
Can you check the logfile if you see errors?
You mentioned the bootstrap file, did you use that? You can find instructions here: https://wiki.veriblock.org/index.php/NodeCore_Bootstrap_File
Please consider joining the Veriblock Discord where support is available: https://discord.gg/wJZEjry

**Comment by xjqxzyr** [comment]
Yes,Is a bug

**Comment by Leonardiae** [comment]
Can you provide more details?

**Comment by BernatCarbo** [comment]
This issue seems to be very outdated, the nodecore package now comes with the bootstrap-downloader tool which allows you to download the block files relatively fast, please open another issue if you still having problems with the sync process.
