### ISSUE TITLE
Is nodecore could adjust peer ban threhhold by config file?

### ISSUE THREAD

**Issue by yyj-zz** [VeriBlock/nodecore-releases#130]
When i start a GPU miner pool ,there only one miner machine is connected to the pool ,first ,everything is allright,but it has runned for 4 minutes, there server thown an error：ucp clinet has exceeded the ban threshold.

Is there have a way to adjust the ban threshold for Warden value?

**Comment by BernatCarbo** [comment]
You can change the ban threshold with next configuration: ```ucp.ban.threshold``` (100 by default)
