### ISSUE TITLE
last version wallet not worked

### ISSUE THREAD

**Issue by BARUCHER777** [VeriBlock/nodecore-releases#131]
Installed all types of Java libraries, but the wallet still can't start!

![java-error-123](https://user-images.githubusercontent.com/18327150/95447742-e3534280-096a-11eb-894d-7ddbe8383a98.jpg)

**Comment by Leonardiae** [comment]
According to wiki https://wiki.veriblock.org/index.php/GUI_Wallet:

`Java 13 or later, such as OpenJDK 14 from https://adoptopenjdk.net. You should choose version OpenJDK 14 (Latest) using the HotSpot JVM.`

Have you tried that?

**Comment by BARUCHER777** [comment]
An error occurred while trying to start a node ....
All possible libraries for Java are already installed on the system




![VerBlock-error-12345](https://user-images.githubusercontent.com/18327150/95478483-3bea0600-0992-11eb-9f17-a898484f7fd7.jpg)

**Comment by BernatCarbo** [comment]
That's a different issue and I think that it was already resolved, please create a new issue if not.
