### ISSUE TITLE
nodecore-cli-0.2.0 r4 CLI up arrow doesn't return last command in Linux

### ISSUE THREAD

**Issue by Hou5e** [VeriBlock/nodecore-releases#14]
nodecore-cli-0.2.0 r4 CLI up arrow doesn't return last command in Linux, but does in Windows:

![image](https://user-images.githubusercontent.com/20870053/42727237-c77d4d68-8757-11e8-9e83-7c817623d006.png)

**Comment by a123b** [comment]
Version 0.2.17 fixes it. And the colors are now working, too. Great job on this cli update, it's _so_ much more usable now!

There's no space between the `>` and the entered command anymore, though. Is this intentional? I think it looks kind of weird...
