### ISSUE TITLE
PoP miner not working in stand-alone mode

### ISSUE THREAD

**Issue by Bambarello** [VeriBlock/nodecore-releases#15]
Seems to have POP mining continuous the command "MINE" should be sent to POP miner every time, otherwise it's just waiting for command.

Please add to POP miner command-line option, like --mine, which will run one instance of POP miner, will submit transaction to the net, and then (as I understood) POP miner to close. Then this command can be added to CRONTAB and executed every certain time.

Attached are POP miner logs showing it's not working regularly, just after command MINE execution.

[bitcoinj.nodecore-pop.log.zip](https://github.com/VeriBlock/nodecore-releases/files/2195161/bitcoinj.nodecore-pop.log.zip)
[veriblock.nodecore-pop.log.zip](https://github.com/VeriBlock/nodecore-releases/files/2195159/veriblock.nodecore-pop.log.zip)
[veriblock.nodecore-error.log.gz](https://github.com/VeriBlock/nodecore-releases/files/2195160/veriblock.nodecore-error.log.gz)

**Comment by JoshRack** [comment]
Thanks for the submitting. Take a look at https://wiki.veriblock.org/index.php?title=HowTo_run_PoP_Miner#How_to_set_up_a_cron_schedule_for_mining. There's a built-in cron scheduler to the miner. You can set up a schedule and leave the application running. It effectively invoke the "mine" command at whatever schedule you specify.

**Comment by Hou5e** [comment]
There is a configuration property you can set to run the POP miner every 30 minutes with the cron setting. The 'pop.cron.schedule' setting is not set by default. If you were spending real BTC, it might get expensive with that setting... ~$2/POP at 200sats/byte and $6200/BTC.
See the FAQ at the bottom of this page: https://wiki.veriblock.org/index.php?title=HowTo_run_PoP_Miner

An example ncpop.properties file would look like this (without the .txt extension): 
[ncpop.properties.txt](https://github.com/VeriBlock/nodecore-releases/files/2195187/ncpop.properties.txt)
