### ISSUE TITLE
PoP mining seems expensive

### ISSUE THREAD

**Issue by Hou5e** [VeriBlock/nodecore-releases#16]
With testnet BTC the PoP costs are nothing, but if you were using real BTC the PoP transactions costs seem like they could be really high, unless I'm missing something.

Using a miner fee of ~200 sat/byte, Testnet BTC diff for PoP transaction: 0.00035577 BTC (@ $6234/BTC) = $2.22 / PoP transaction

Is there any plan to use bundled transactions, Segwit, Lightning, or something cheaper.
Also, it seems like BTC mempool is going to get spammed with so many transactions from lots of VeriBlock miners. Coming up with a better way to reduce that, seems like it would be beneficial to everyone involved.

**Comment by gsxryan** [comment]
I fail to see the incentive to PoP when you risk your BTC, for a chance at VBK.  It feels like loading it into a slot machine.  Unless you got the same in USD back, plus a bonus.  PoPing valuable BTC will have to be very communicative / stat driven to take the plunge.

I burned through 0.2testnet BTC in about a day or two before it stopped working for me.  Hou5e's market price above would make that $1200.

**Comment by Hou5e** [comment]
How about adding an additional cheaper blockchain to PoP mine on (PoP reward price adjusted to be less), in addition to BTC?

If you used CureCoin 1.0, it would give more utility to CureCoin 1.0, and would add cheaper PoP transactions to VeriBlock. 

There is a CureCoin java library that would also probably be useful, if you want to try it (one of the FoldingCoin guys made it):   https://github.com/Epoxide-Folding/CureCoinJ

**Comment by ArtemBernatskyy** [comment]
@JoshRack I'm sorry but why this issue was closed ?

**Comment by CRYPTOSeattle** [comment]
Tried this on the VBK mainnet (just went online) and have found that PoP mining is indeed prohibitively expensive IMO. Would love to hear input on why I'm wrong and how to profit though. Anybody have an answer?
