### ISSUE TITLE
multiple instances running pop-no btc available

### ISSUE THREAD

**Issue by shiggidydog** [VeriBlock/nodecore-releases#24]
While running multiple instances, if i have 4 btc in the wallet and they are all using that wallet. Eventually one of them will error with not enough btc to conduct pop.  Is there a reason why others are "locking" up the full amount of btc?  Is it due to sending btc out and the change not back in the wallet yet?

**Comment by JoshRack** [comment]
That's correct. When running multiple instances of the PoP miner, each instance should have its own BTC wallet.
