### ISSUE TITLE
add ("In-Sync") to the pool page next to the (Blockchain Height)

### ISSUE THREAD

**Issue by shiggidydog** [VeriBlock/nodecore-releases#27]
would be nice to know at quick glance that my blockchain height matches the dev pool's blockchain height.  It would be much faster to recognize that my local chain has forked.  So if we don't see that message "in sync" maybe in green font, then it can show "out of sync" in red and have a tolerance of 3 to 4 blocks? Just in case there is a slight delay in propagation.

**Comment by JoshRack** [comment]
Pool consistency issues have been addressed.
