### ISSUE TITLE
PoP mining cron job can start mining before the PoP Ready message

### ISSUE THREAD

**Issue by Hou5e** [VeriBlock/nodecore-releases#30]
The PoP mining cron job can start mining before the: 'SUCCESS: PoP Miner: READY' message.

This can easily be seen if you change the cron job time interval from 30 minutes to 2 minutes, and especially with a slower / more saturated internet connection.

Not starting the cron job timer until after the POP mining Ready message would probably help avoid issues during the PoP mining startup phase.

**Comment by JoshRack** [comment]
This has been implemented
