### ISSUE TITLE
[GPU MINER] Wide Swings in Power Consumption

### ISSUE THREAD

**Issue by dumbcrypt0** [VeriBlock/nodecore-releases#34]
While monitoring my GPU in Afterburner (currently no overclock, only using it for monitoring), I am seeing a wide range of fluctuation in power%. Swings are as far as 33% on the monitor to 103%. No adjustments have been made to TDP settings.  By comparison, running Ethash, I see nearly no fluctuation (perhaps a couple of % up or down). My own uneducated guess is that this may be the result of the GPU miner being throttled and would therefore be temporary. If that is not the case, then this could lead to stability issues.

**Comment by JoshRack** [comment]
GPU has been open sourced. If still an issue, raise here: [https://github.com/VeriBlock/nodecore-pow-cuda-miner](https://github.com/VeriBlock/nodecore-pow-cuda-miner)
