### ISSUE TITLE
NodeCore randomly exits

### ISSUE THREAD

**Issue by protovist** [VeriBlock/nodecore-releases#42]

**Comment by protovist** [comment]
Jul 18 04:02:56 vbk-node nodecore[8877]: 04:02:56.006 [grpc-default-executor-3077] INFO  nodecore.d.k - Add transa
ction received from 45.32.212.234
Jul 18 04:02:56 vbk-node nodecore[8877]: 04:02:56.006 [grpc-default-executor-3036] INFO  nodecore.d.k - Message '2
602961' acknowledged by 73.98.184.221'
Jul 18 04:02:56 vbk-node nodecore[8877]: 04:02:56.006 [grpc-default-executor-3036] INFO  nodecore.d.k - Message '2
603022' acknowledged by 73.98.184.221'
Jul 18 04:02:56 vbk-node nodecore[8877]: 04:02:56.006 [grpc-default-executor-3098] INFO  nodecore.d.k - Add transa
ction received from 73.51.214.205
Jul 18 04:02:56 vbk-node nodecore[8877]: 04:02:56.006 [grpc-default-executor-3036] INFO  nodecore.d.k - Message '2
603024' acknowledged by 73.98.184.221'
Jul 18 04:02:56 vbk-node nodecore[8877]: 04:02:56.006 [grpc-default-executor-3114] INFO  nodecore.d.k - Add transa
ction received from 13.125.232.22
Jul 18 04:02:56 vbk-node nodecore[8877]: 04:02:56.007 [grpc-default-executor-3049] INFO  nodecore.d.k - Add transa
ction received from 149.28.61.52
Jul 18 04:02:56 vbk-node nodecore[8877]: 04:02:56.007 [grpc-default-executor-3036] INFO  nodecore.d.k - Message '2
603066' acknowledged by 73.98.184.221'
Jul 18 04:02:56 vbk-node nodecore[8877]: 04:02:56.007 [grpc-default-executor-3114] INFO  nodecore.d.k - Message '2
603075' acknowledged by 73.98.184.221'
Jul 18 04:02:56 vbk-node nodecore[8877]: 04:02:56.007 [grpc-default-executor-3036] INFO  nodecore.d.k - Message '2
603122' acknowledged by 35.196.246.194'
Jul 18 04:02:56 vbk-node nodecore[8877]: 04:02:56.007 [grpc-default-executor-3098] INFO  nodecore.d.k - Add block
000000000B628DC2A72B219F986E9A1597059354FD6CF1D7 @ 16256 received from 13.125.232.22
Jul 18 04:02:56 vbk-node nodecore[8877]: 04:02:56.007 [grpc-default-executor-3077] INFO  nodecore.d.k - Message '2
603076' acknowledged by 73.98.184.221'
Jul 18 04:02:56 vbk-node nodecore[8877]: 04:02:56.007 [grpc-default-executor-3036] INFO  nodecore.d.k - Message '2
603099' acknowledged by 73.98.184.221'
Jul 18 04:02:58 vbk-node systemd[1]: vbk-node.service: Main process exited, code=exited, status=1/FAILURE
Jul 18 04:02:58 vbk-node systemd[1]: vbk-node.service: Failed with result 'exit-code'.

**Comment by JoshRack** [comment]
Most of the code in the stack trace no longer exists.
