### ISSUE TITLE
Explain Network requirements to establish peer connections [lots of failed to establish connection]

### ISSUE THREAD

**Issue by gsxryan** [VeriBlock/nodecore-releases#43]
Firewall does not use Hairpin NAT, or UPnP.
Noticing firewall blocking port 6501 connection attempts.
```
23:11:01 | Default DROP | TCP |   | 146.241.80.106:25434 | 146.241.80.106 | : | 25434 | → | WANIP:6501 | WANIP | : | 6501 |   | [SYN]len=52ttl=105tos=0x00srcmac=dstmac= | [SYN] | len=52 | ttl=105 | tos=0x00 | 
```

NodeCore Shows failed to est. connections:
```
23:08:00.310 [pool-4-thread-1] INFO  nodecore.d.i - Opening connection to 149.28.245.58
23:08:00.311 [pool-4-thread-1] INFO  nodecore.d.i - Opening connection to 149.28.243.13
23:08:00.322 [pool-4-thread-1] INFO  nodecore.d.i - Opening connection to 45.32.207.211
23:08:00.325 [grpc-default-executor-29] INFO  nodecore.d.m - Failed to establish connection with 149.28.245.58
23:08:00.326 [grpc-default-executor-30] INFO  nodecore.d.m - Failed to establish connection with 149.28.243.13
23:08:00.337 [grpc-default-executor-30] INFO  nodecore.d.m - Failed to establish connection with 45.32.207.211
```

Forwarded all 6501 TCP packets to the Nodecore machine, but it fails to establish connections regardless.

Please define the network requirements without support for UPnP or Hairpin NAT.  Or, is this an expected common message from all clients?

**Comment by gsxryan** [comment]
Max suggested on the Telegram to run from CLI: 
I am currently monitoring after this change.
```
addnode 176.9.30.210:6501
```

**Comment by timstall** [comment]
FYI, this could be a case of a previous peer is no longer available - not as much a "Failed". Newer NC version updates the log message.

**Comment by gsxryan** [comment]
I agree with that.  I'll keep an eye on the new version. So far I'm getting a lot less errors, and have seen coinbase payouts again.

**Comment by gsxryan** [comment]
Newer NC Versions seem to have resolved
