### ISSUE TITLE
GPU Miner crashes on bad server response

### ISSUE THREAD

**Issue by protovist** [VeriBlock/nodecore-releases#44]
Resource Utilization: HIGH
NVML Status: DISABLED
Share Type: CPU
Benchmark Mode: DISABLED
Attempting to mine to pool 35.237.206.228:8501 with username V2SxFzwDFYn5VuLFWLvRrQLdyB4Ed8 and password ...
The specified server supports all necessary commands (bitflag: 10011111111)
Successfully authenticated to server!
Successfully subscribed to server!
1420
An error has been encountered while reading a command!
An error has been encountered while reading a command!
Command: {"command":"MINING_JOB","request_id":{"type":"REQUEST_ID","data":1423328386},"job_id":{"type":"JOB_ID","data":377},"block_index":{"type":"BLOCK_INDEX","data":18220},"block_version":{"type":"BLOCK_VERSION","data":1},"previous_block_hash":{"type":"BLOCK_HASH","data":"000000000D8360A691F508CD17838F7390449DA69966EFD9"},"second_previous_block_hash":{"type":"BLOCK_HASH","data":"000000000CD05D080E22F0A04164189C38205C96BF713B92"},"third_previous_block_hash":{"type":"BLOCK_HASH","data":"0000000004252A43469C34D87F0058019C7F5338BE571DDD"},"pool_address":{"type":"ADDRESS","data":"V2C86eV6xi1uPykYPNnP8nWwu9GJxf"},"merkle_root":{"type":"TOP_LEVEL_MERKLE_ROOT","data":"87F4B394E79F8FB47E7D743232FC1F6AE3BAAD026CC9F1CA"},"timestamp":{"type":"TIMESTAMP","data":1531939597},"difficulty":{"type":"DIFFICULTY","data":84702804},"mining_target":{"type":"TARGET","data":"000000ffffffffffffffffffffffffffffffffffffffffff"},"ledger_hash":{"type":"LEDGER_HASH","data":"AB8A9731C82B25AA3A5ECF6008B1BFCD09196FB23CC6DBF8"},"coinbase_txid":{"type":"TRANSACTION_ID","data":"8E50C9910512A64235879EC3746B3D3D362989C87D96B88BC8F8F496987D7806"},"pop_datastore_hash":{"type":"POP_DATASTORE_HASH","data":"F5A5FD42D16A20302798EF6ED309979B43003D2320D9F0E8EA9831A92759FB4B"},"miner_comment":{"type":"MINER_COMMENT","data":""},"pop_transaction_merkle_root":{"type":"INTERMEDIATE_LEVEL_MERKLE_ROOT","data":"00000000000000000000000000000000000000000000000
Error: syntax error at line 1 near:
An error has occurred while attempting to read the server response: syntax error at line 1 near:

**Comment by protovist** [comment]
40DF854FBAC8757A13E85AD35CA6B1C080"},"coinbase_txid":{"type":"TRANSACTION_ID","data":"F25D88618544B7A767222391A359C6C57A717E7512A557004368CB83151FCB9C"},"pop_datastore_hash":{"type":"POP_DATASTORE_HASH","data":"F5A5FD42D16A20302798EF6ED309979B43003D2320D9F0E8EA9831A92759FB4B"},"miner_comment":{"type":"MINER_COMMENT","data":""},"pop_transaction_merkle_root":{"type":"INTERMEDIATE_LEVEL_MERKLE_ROOT","data":"00000000000000000000000000000000000000000000000   [GPU #0 (Tesla V100-SXM2-16GB)]:
 CORE: -1   Error:  MEMORY: -1   syntax error at line 1 near:  TEMP: -1C

                                    Avg. Hashrate: 345.000000 MH/second
                                    Share History: An error has occurred while attempting to read the server response: syntax error at line 1 near: 112/
113/115 (99.115%)
------------------------------------------------------------------------------------------------------------------------     Extra Nonce: 24000000    Job ID: 384    Encoded Difficulty: 84702804
     Last Block:        000000001355621768D26785CB30B56127F5CFC4BBAB8631
     Merkle Root:       160AAC603F2F52B7A65347279FF03DC4D8265FCE49F0AA9D
------------------------

**Comment by protovist** [comment]
The submitted share was stale!"}}
{"command":"MINING_SUBMIT_FAILURE","request_id":{"type":"REQUEST_ID","data":2500466},"reason":{"type":"MESSAGE","data":"The submitted share was stale!"}}
{"command":"MINING_SUBMIT_FAILURE","request_id":{"type":"REQUEST_ID","data":2500467},"reason":{"type":"MESSAGE","data":"The submitted share was stale!"}}
{"command":"MINING_SUBMIT_FAILURE","request_id":{"type":"REQUEST_ID","data":2500468},"reason":{"type":"MESSAGE","data":"The submitted share was stale!"}}
626
Encoded Difficulty: Error: 84702804syntax error at line 1 near: GE","data":"The submitted share was stale!"}}
     Last Block:
Top-level line GE","data":"The submitted share was stale!"}}

**Comment by gsxryan** [comment]
```
[WARN]  THE MINING POOL HAS STOPPED RESPONDING TO OUR SUBMISSIONS!
 [ERROR]  Submitting a share failed for the following reason: The submitted share was stale!
 [ERROR]  Submitting a share failed for the following reason: The submitted share was stale!
```

**Comment by JoshRack** [comment]
Closing in this repo. If this is still an issue, please reopen at [https://github.com/VeriBlock/nodecore-pow-cuda-miner](https://github.com/VeriBlock/nodecore-pow-cuda-miner)
