### ISSUE TITLE
Node should not calculate block template until mining enabled

### ISSUE THREAD

**Issue by michael-kernel-sanders** [VeriBlock/nodecore-releases#51]
04:12:45.551 [pool-10-thread-1] INFO  nodecore.core.a.k - Added a new block (00000000009D4A2C838CFF1319A417BDF8DFB2
9DD4CFA6AC @ 13049) to best chain.
04:12:45.551 [pool-10-thread-1] INFO  nodecore.core.a.k - Calculating block template for block 13050!
04:12:45.554 [pool-10-thread-1] INFO  nodecore.core.a.k - Has not seen 0000000000813132BCE05D3D1522891F26367E21CA6B
E44A
04:12:45.670 [pool-3-thread-1] INFO  nodecore.d.i - Opening connection to 45.77.173.59
04:12:45.907 [grpc-default-executor-51] INFO  nodecore.d.m - Failed to establish connection with 45.77.173.59
04:12:46.099 [pool-10-thread-1] INFO  nodecore.core.a.k - Before applying block 13050(0000000000813132BCE05D3D15228
91F26367E21CA6BE44A), latest Bitcoin block known: 0000000000000035B43F523828F38F5C97E5E34C524F7971940602D9C7D425ED
04:12:46.099 [pool-10-thread-1] INFO  nodecore.core.a.k - When adding block 13050 (0000000000813132BCE05D3D1522891F
26367E21CA6BE44A), we are also adding 3 Bitcoin blocks.
04:12:46.143 [pool-10-thread-1] INFO  nodecore.core.a.k - Added a new block (0000000000813132BCE05D3D1522891F26367E
21CA6BE44A @ 13050) to best chain.
04:12:46.144 [pool-10-thread-1] INFO  nodecore.core.a.k - Calculating block template for block 13051!
04:12:46.147 [pool-10-thread-1] INFO  nodecore.core.a.k - Has not seen 000000000DB8E714A88E7A9EB1ED7402250FD975F586
AE52
04:12:46.689 [pool-10-thread-1] INFO  nodecore.core.a.k - Before applying block 13051(000000000DB8E714A88E7A9EB1ED7
402250FD975F586AE52), latest Bitcoin block known: 0000000000000027A7832C272DF5B37D12CD17C07C18B0F8694197B5097405E2
04:12:46.690 [pool-10-thread-1] INFO  nodecore.core.a.k - When adding block 13051 (000000000DB8E714A88E7A9EB1ED7402
250FD975F586AE52), we are also adding 1 Bitcoin blocks.
04:12:46.713 [pool-10-thread-1] INFO  nodecore.core.a.k - Added a new block (000000000DB8E714A88E7A9EB1ED7402250FD9
75F586AE52 @ 13051) to best chain.
04:12:46.713 [pool-10-thread-1] INFO  nodecore.core.a.k - Calculating block template for block 13052!
04:12:46.717 [pool-10-thread-1] INFO  nodecore.core.a.k - Has not seen 000000000127E04819DF63B1AD8E30547F0E6916E9BF
152D
04:12:47.063 [pool-3-thread-1] INFO  nodecore.d.i - Opening connection to 45.76.47.119
04:12:47.268 [pool-10-thread-1] INFO  nodecore.core.a.k - Before applying block 13052(000000000127E04819DF63B1AD8E3
0547F0E6916E9BF152D), latest Bitcoin block known: 0000000000000004731A85389A3C841F9FC85CC9A991BDA9F73EC12361075872
04:12:47.269 [pool-10-thread-1] INFO  nodecore.core.a.k - When adding block 13052 (000000000127E04819DF63B1AD8E3054
7F0E6916E9BF152D), we are also adding 1 Bitcoin blocks.
04:12:47.304 [pool-10-thread-1] INFO  nodecore.core.a.k - Added a new block (000000000127E04819DF63B1AD8E30547F0E69
16E9BF152D @ 13052) to best chain.
04:12:47.304 [pool-10-thread-1] INFO  nodecore.core.a.k - Calculating block template for block 13053!

**Comment by JoshRack** [comment]
Implemented.
