### ISSUE TITLE
Compile GPU PoW miner using Cuda 9.0

### ISSUE THREAD

**Issue by appkoders** [VeriBlock/nodecore-releases#52]
Please compile the GPU PoW miner using Cuda 9.0 as some of my machines are still using Cuda 9.0 and dont want to change them as they are stable using those driver. 

Using Cuda 9.2 doesnt really give you faster hashrates based on my tests, but I could be wrong.

**Comment by JoshRack** [comment]
GPU miner has been open-sourced at [https://github.com/VeriBlock/nodecore-pow-cuda-miner](https://github.com/VeriBlock/nodecore-pow-cuda-miner)
