### ISSUE TITLE
[NodeCore] Extremely high CPU utilization while pool is running

### ISSUE THREAD

**Issue by a123b** [VeriBlock/nodecore-releases#55]
Lately, NodeCore is constantly using 75-100% CPU after the pool is started.
Nothing particularly suspicious in the log file, there's just a high amount of transactions being processed.
Maybe the block template is just updated too frequently?

**Comment by oglaucio** [comment]
I've noticed that my CPU load was high as well while running only nodecore and PoPMiner. After stopping it (core), deleting tcache.csh and nodecore.dat and re-starting core, CPU usage went back to normal (around 15%).

**Comment by a123b** [comment]
As the CPU wasn't really used by the pool but rather for endless garbage collection as a result of the memory leaks, I'm, closing this as a duplicate of #75.
