### ISSUE TITLE
Block Explorer does not always show coinbase

### ISSUE THREAD

**Issue by protovist** [VeriBlock/nodecore-releases#6]
The Block Explorer only seems to show the coinbase transaction if there are other transactions in the block.

<img width="886" alt="screen shot 2018-07-13 at 2 01 07 pm" src="https://user-images.githubusercontent.com/28274193/42713745-5dd737fa-86a5-11e8-882a-106990d549f0.png">

**Comment by JoshRack** [comment]
The block explorer doesn't show the actual coinbase transaction currently.  It is something we plan to add soon. When you see a transaction that looks like it might be a coinbase transaction, it is actually a mining pool paying out to its contributors for a previously mined block.

Thanks for bringing this up!
