### ISSUE TITLE
[Nodecore 0.2.2] Exception in thread "main" java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by Sir-Thiago** [VeriBlock/nodecore-releases#60]
>  2018-07-20 09:41:27,334 ERROR [grpc-default-worker-ELG-3-1] i.n.u.ResourceLeakDetector [Slf4JLogger.java:171] LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
> Recent access records: 
> 2018-07-20 22:36:42,936 ERROR [grpc-default-worker-ELG-3-1] i.n.u.c.D.rejectedExecution [Slf4JLogger.java:181] Failed to submit a listener notification task. Event loop shut down?
> java.util.concurrent.RejectedExecutionException: event executor terminated
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:821)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:327)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:320)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:746)
> 	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:760)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)
> 	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
> 	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
> 	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1148)
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:490)
> 	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
> 	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
> 	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:331)
> 	at io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:234)
> 	at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:219)
> 	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:31)
> 	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:216)
> 	at io.grpc.internal.InternalSubchannel.access$500(InternalSubchannel.java:51)
> 	at io.grpc.internal.InternalSubchannel$1EndOfCurrentBackoff.run(InternalSubchannel.java:241)
> 	at io.grpc.internal.LogExceptionRunnable.run(LogExceptionRunnable.java:41)
> 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
> 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
> 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
> 	at java.lang.Thread.run(Unknown Source)
> 2018-07-20 22:36:43,576 ERROR [grpc-default-worker-ELG-3-1] i.n.u.c.D.rejectedExecution [Slf4JLogger.java:181] Failed to submit a listener notification task. Event loop shut down?
> java.util.concurrent.RejectedExecutionException: event executor terminated
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:821)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:327)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:320)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:746)
> 	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:760)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)
> 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:987)
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:491)
> 	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
> 	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
> 	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:331)
> 	at io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:234)
> 	at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:219)
> 	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:31)
> 	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:216)
> 	at io.grpc.internal.InternalSubchannel.access$500(InternalSubchannel.java:51)
> 	at io.grpc.internal.InternalSubchannel$1EndOfCurrentBackoff.run(InternalSubchannel.java:241)
> 	at io.grpc.internal.LogExceptionRunnable.run(LogExceptionRunnable.java:41)
> 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
> 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
> 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
> 	at java.lang.Thread.run(Unknown Source)
> 2018-07-20 22:36:44,217 ERROR [grpc-default-worker-ELG-3-1] i.n.u.c.D.rejectedExecution [Slf4JLogger.java:181] Failed to submit a listener notification task. Event loop shut down?
> java.util.concurrent.RejectedExecutionException: event executor terminated
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:821)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:327)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:320)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:746)
> 	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:760)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)
> 	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:113)
> 	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87)
> 	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1010)
> 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:825)
> 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
> 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
> 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1041)
> 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
> 	at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:248)
> 	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:31)
> 	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:216)
> 	at io.grpc.internal.InternalSubchannel.access$500(InternalSubchannel.java:51)
> 	at io.grpc.internal.InternalSubchannel$1EndOfCurrentBackoff.run(InternalSubchannel.java:241)
> 	at io.grpc.internal.LogExceptionRunnable.run(LogExceptionRunnable.java:41)
> 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
> 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
> 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
> 	at java.lang.Thread.run(Unknown Source)
> 2018-07-20 22:36:44,217 ERROR [grpc-default-worker-ELG-3-1] i.n.u.c.D.rejectedExecution [Slf4JLogger.java:181] Failed to submit a listener notification task. Event loop shut down?
> java.util.concurrent.RejectedExecutionException: event executor terminated
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:821)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:327)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:320)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:746)
> 	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:760)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)
> 	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:163)
> 	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
> 	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
> 	at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:248)
> 	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:31)
> 	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:216)
> 	at io.grpc.internal.InternalSubchannel.access$500(InternalSubchannel.java:51)
> 	at io.grpc.internal.InternalSubchannel$1EndOfCurrentBackoff.run(InternalSubchannel.java:241)
> 	at io.grpc.internal.LogExceptionRunnable.run(LogExceptionRunnable.java:41)
> 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
> 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
> 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
> 	at java.lang.Thread.run(Unknown Source)
> 2018-07-20 22:36:44,841 ERROR [grpc-default-worker-ELG-3-1] i.n.u.c.D.rejectedExecution [Slf4JLogger.java:181] Failed to submit a listener notification task. Event loop shut down?
> java.util.concurrent.RejectedExecutionException: event executor terminated
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:821)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:327)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:320)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:746)
> 	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:760)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)
> 	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:113)
> 	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87)
> 	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1010)
> 	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:532)
> 	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:512)
> 	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:450)
> 	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:958)
> 	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:223)
> 	at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:259)
> 	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:31)
> 	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:216)
> 	at io.grpc.internal.InternalSubchannel.access$500(InternalSubchannel.java:51)
> 	at io.grpc.internal.InternalSubchannel$1EndOfCurrentBackoff.run(InternalSubchannel.java:241)
> 	at io.grpc.internal.LogExceptionRunnable.run(LogExceptionRunnable.java:41)
> 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
> 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
> 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
> 	at java.lang.Thread.run(Unknown Source)
> 2018-07-20 22:42:13,891 ERROR [ForkJoinPool.commonPool-worker-1] o.v.c.c.Crypto [Crypto.java:35] Unhandled exception
> java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: SHA-256, provider: SUN, class: sun.security.provider.SHA2$SHA256)
> 	at java.security.Provider$Service.newInstance(Unknown Source)
> 	at sun.security.jca.GetInstance.getInstance(Unknown Source)
> 	at sun.security.jca.GetInstance.getInstance(Unknown Source)
> 	at java.security.Security.getImpl(Unknown Source)
> 	at java.security.MessageDigest.getInstance(Unknown Source)
> 	at org.veriblock.core.crypto.Crypto.<init>(Crypto.java:33)
> 	at nodecore.core.transactions.g.b(TransactionUtility.java:410)
> 	at nodecore.core.transactions.g.a(TransactionUtility.java:396)
> 	at nodecore.core.transactions.g.b(TransactionUtility.java:535)
> 	at nodecore.core.a.i.<init>(DefaultBlock.java:281)
> 	at nodecore.core.a.i.<init>(DefaultBlock.java:382)
> 	at nodecore.core.a.i.<init>(DefaultBlock.java:374)
> 	at nodecore.core.a.i$$FastClassByGuice$$77582dfa.newInstance(<generated>)
> 	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
> 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
> 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
> 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
> 	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
> 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
> 	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
> 	at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:776)
> 	at com.sun.proxy.$Proxy16.a(Unknown Source)
> 	at nodecore.core.a.k.a(DefaultBlockchain.java:203)
> 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
> 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
> 	at java.util.stream.Nodes$SizedCollectorTask.compute(Unknown Source)
> 	at java.util.concurrent.CountedCompleter.exec(Unknown Source)
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source)
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
> Caused by: java.lang.OutOfMemoryError: Java heap space
> 	at sun.security.provider.SHA2.<init>(Unknown Source)
> 	at sun.security.provider.SHA2$SHA256.<init>(Unknown Source)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
> 	at java.security.Provider$Service.newInstance(Unknown Source)
> 	at sun.security.jca.GetInstance.getInstance(Unknown Source)
> 	at sun.security.jca.GetInstance.getInstance(Unknown Source)
> 	at java.security.Security.getImpl(Unknown Source)
> 	at java.security.MessageDigest.getInstance(Unknown Source)
> 	at org.veriblock.core.crypto.Crypto.<init>(Crypto.java:33)
> 	at nodecore.core.transactions.g.b(TransactionUtility.java:410)
> 	at nodecore.core.transactions.g.a(TransactionUtility.java:396)
> 	at nodecore.core.transactions.g.b(TransactionUtility.java:535)
> 	at nodecore.core.a.i.<init>(DefaultBlock.java:281)
> 	at nodecore.core.a.i.<init>(DefaultBlock.java:382)
> 	at nodecore.core.a.i.<init>(DefaultBlock.java:374)
> 	at nodecore.core.a.i$$FastClassByGuice$$77582dfa.newInstance(<generated>)
> 	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
> 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
> 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
> 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
> 	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
> 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
> 	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
> 	at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:776)
> 	at com.sun.proxy.$Proxy16.a(Unknown Source)
> 	at nodecore.core.a.k.a(DefaultBlockchain.java:203)
> 	at nodecore.core.a.k$$Lambda$15/15572076.apply(Unknown Source)
> 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
> <

[veriblock.nodecore-error.log](https://github.com/VeriBlock/nodecore-releases/files/2217094/veriblock.nodecore-error.log)

Java Version 8 Update 181
Win 10

**Comment by JoshRack** [comment]
No longer relevant.
