### ISSUE TITLE
[PoP Miner] RuntimeException on PoP Miner

### ISSUE THREAD

**Issue by oglaucio** [VeriBlock/nodecore-releases#62]
While running PoP miner, I received the following java error:

> 22:18:24.624 [grpc-default-executor-51] WARN  nodecore.d.k - Event stream error from 18.218.236.173: Status{code=CANCELLED, description=Failed to read message., cause=io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
>         at io.grpc.Status.asRuntimeException(Status.java:517)
>         at io.grpc.protobuf.lite.ProtoLiteUtils$2.parse(ProtoLiteUtils.java:174)
>         at io.grpc.protobuf.lite.ProtoLiteUtils$2.parse(ProtoLiteUtils.java:88)
>         at io.grpc.MethodDescriptor.parseResponse(MethodDescriptor.java:265)
>         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:530)
>         at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
>         at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
>         at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:115)
>         at com.google.protobuf.CodedInputStream$ArrayDecoder.skipField(CodedInputStream.java:686)
>         at nodecore.api.grpc.VeriBlockMessages$Transaction.<init>(VeriBlockMessages.java:12929)
>         at nodecore.api.grpc.VeriBlockMessages$Transaction.<init>(VeriBlockMessages.java:12885)
>         at nodecore.api.grpc.VeriBlockMessages$Transaction$1.parsePartialFrom(VeriBlockMessages.java:14962)
>         at nodecore.api.grpc.VeriBlockMessages$Transaction$1.parsePartialFrom(VeriBlockMessages.java:14957)
>         at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:911)
>         at nodecore.api.grpc.VeriBlockMessages$SignedTransaction.<init>(VeriBlockMessages.java:2536)
>         at nodecore.api.grpc.VeriBlockMessages$SignedTransaction.<init>(VeriBlockMessages.java:2477)
>         at nodecore.api.grpc.VeriBlockMessages$SignedTransaction$1.parsePartialFrom(VeriBlockMessages.java:3179)
>         at nodecore.api.grpc.VeriBlockMessages$SignedTransaction$1.parsePartialFrom(VeriBlockMessages.java:3174)
>         at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:911)
>         at nodecore.api.grpc.VeriBlockMessages$TransactionUnion.<init>(VeriBlockMessages.java:15073)
>         at nodecore.api.grpc.VeriBlockMessages$TransactionUnion.<init>(VeriBlockMessages.java:15017)
>         at nodecore.api.grpc.VeriBlockMessages$TransactionUnion$1.parsePartialFrom(VeriBlockMessages.java:16001)
>         at nodecore.api.grpc.VeriBlockMessages$TransactionUnion$1.parsePartialFrom(VeriBlockMessages.java:15996)
>         at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:911)
>         at nodecore.api.grpc.VeriBlockMessages$Block.<init>(VeriBlockMessages.java:27186)
>         at nodecore.api.grpc.VeriBlockMessages$Block.<init>(VeriBlockMessages.java:27078)
>         at nodecore.api.grpc.VeriBlockMessages$Block$1.parsePartialFrom(VeriBlockMessages.java:29261)
>         at nodecore.api.grpc.VeriBlockMessages$Block$1.parsePartialFrom(VeriBlockMessages.java:29256)
>         at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:911)
>         at nodecore.api.grpc.VeriBlockMessages$Event.<init>(VeriBlockMessages.java:46636)
>         at nodecore.api.grpc.VeriBlockMessages$Event.<init>(VeriBlockMessages.java:46592)
>         at nodecore.api.grpc.VeriBlockMessages$Event$1.parsePartialFrom(VeriBlockMessages.java:49106)
>         at nodecore.api.grpc.VeriBlockMessages$Event$1.parsePartialFrom(VeriBlockMessages.java:49101)
>         at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:91)
>         at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
>         at io.grpc.protobuf.lite.ProtoLiteUtils$2.parseFrom(ProtoLiteUtils.java:179)
>         at io.grpc.protobuf.lite.ProtoLiteUtils$2.parse(ProtoLiteUtils.java:171)
>         ... 8 more
> }
Running locally on windows...nodecore running with 8Gb in .bat file.
Java:
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

**Comment by JoshRack** [comment]
I don't believe this is still applicable.
