### ISSUE TITLE
Rotation logs on the GPU miner

### ISSUE THREAD

**Issue by 0dy55ey** [VeriBlock/nodecore-releases#67]
The log of the miner reaches hight sizes, which makes it impossible to control the work process!

**Comment by JoshRack** [comment]
Closing here. The GPU miner has been open-sourced [https://github.com/VeriBlock/nodecore-pow-cuda-miner](https://github.com/VeriBlock/nodecore-pow-cuda-miner) and the equivalent issue exists in that repository.
