### ISSUE TITLE
Error starting nodecore

### ISSUE THREAD

**Issue by 0dy55ey** [VeriBlock/nodecore-releases#68]
Version nodecore-0.2.5
Java latest version 1.8.0_181-b13

Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Application terminated unexpectedly, press any key to exit

CPU: Intel Core i3 6100 - 3.7Ghz
DDR4 8 Gb

**Comment by timstall** [comment]
@0dy55ey - with 0.2.9, is this still an issue?

**Comment by 0dy55ey** [comment]
the problem remains the same in 0.2.9

**Comment by 0dy55ey** [comment]
jdk-10.0.2 from oracle solved the problem!
