### ISSUE TITLE
After stopping and starting my node (0.2.5) IndexOutOfBoundsException

### ISSUE THREAD

**Issue by BigShoots** [VeriBlock/nodecore-releases#69]
`02:03:01.562 [main] INFO  nodecore.core.a.m - About to process block cache...
02:03:01.562 [main] INFO  nodecore.core.a.m - Done processing block cache...
02:03:01.562 [main] INFO  nodecore.core.a.m - About to add block directly...
02:03:01.562 [main] INFO  nodecore.core.a.m - Attempting to add block 0000000004ED8A5B463F371B03BE37691C6132FBCD4224F5 as an alternate chain
02:03:01.576 [main] INFO  nodecore.core.a.m - Added block directly... state: SUCCESSFULLY_ADDED_ALTERNATE_CHAIN
02:03:01.577 [main] INFO  nodecore.core.a.m - Added a new block (0000000004ED8A5B463F371B03BE37691C6132FBCD4224F5 @ 39631)
02:03:01.577 [main] INFO  nodecore.core.a.m - Setting the local blockchain height...
02:03:01.577 [main] INFO  nodecore.core.a.m - Calculating block template for block 39632!
02:03:01.606 [main] INFO  nodecore.core.a.m - Before adding block 39632(00000000026E3C16CDE90597788C41C36FE31015E6E673F1), latest Bitcoin block known: 000000000001B31C7C315CF8EACB2C79EE4CC2C1FD578F9C2358BDBB7822AF92
02:03:01.607 [main] INFO  nodecore.core.a.m - About to process block cache...
02:03:01.607 [main] INFO  nodecore.core.a.m - Done processing block cache...
02:03:01.607 [main] INFO  nodecore.core.a.m - When adding block 39632 (00000000026E3C16CDE90597788C41C36FE31015E6E673F1), we are also adding 2 Bitcoin blocks.
02:03:01.607 [main] INFO  nodecore.core.a.m - About to add block directly...
02:03:01.607 [main] INFO  nodecore.core.a.m - Attempting to add block 00000000026E3C16CDE90597788C41C36FE31015E6E673F1 as an alternate chain
02:03:01.624 [main] INFO  nodecore.core.a.m - Extending the tree while adding a forked block...
02:03:01.625 [main] INFO  nodecore.core.a.m - Added block directly... state: SUCCESSFULLY_ADDED_ALTERNATE_CHAIN_NOW_BEST
02:03:01.625 [main] INFO  nodecore.core.a.m - Added a new block (00000000026E3C16CDE90597788C41C36FE31015E6E673F1 @ 39632), new best block!
02:03:01.639 [main] INFO  nodecore.core.a.m - Found a new best blockchain, ending at block 39632 (00000000026E3C16CDE90597788C41C36FE31015E6E673F1)!
02:03:01.639 [main] INFO  nodecore.core.a.m - Found last common block between the two chains: 39629 -> 00000000068F3A5F2E7D1E6BADC4FFDB20BD082AE5B3C359
02:03:01.639 [main] INFO  nodecore.core.a.m - Unapplying block: 39631 -> 0000000002E849D177E188F3D6ECD0E94F3E2C7FE689F742
02:03:01.639 [main] INFO  nodecore.core.a.m - Ledger hash before unapplying block 39631: EB9B71DD5F02486184E976BBEAA3401CD9E351CE0DBB7503
02:03:01.643 [main] ERROR nodecore.core.a.m - resolveToNewBestChain failed
java.lang.IndexOutOfBoundsException: Index: 39632, Size: 39632
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at nodecore.core.a.m.a(DefaultBlockchain.java:1466)
        at nodecore.core.a.m.c(DefaultBlockchain.java:2018)
        at nodecore.core.a.m.a(DefaultBlockchain.java:1909)
        at nodecore.core.a.m.h(DefaultBlockchain.java:202)
        at nodecore.Program.a(Program.java:84)
        at nodecore.Program.main(Program.java:156)
02:03:01.645 [main] ERROR nodecore.Program - Unable to load blockchain.
java.lang.IndexOutOfBoundsException: Index: 39632, Size: 39632
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at nodecore.core.a.m.a(DefaultBlockchain.java:1466)
        at nodecore.core.a.m.c(DefaultBlockchain.java:2018)
        at nodecore.core.a.m.a(DefaultBlockchain.java:1909)
        at nodecore.core.a.m.h(DefaultBlockchain.java:202)
        at nodecore.Program.a(Program.java:84)
        at nodecore.Program.main(Program.java:156)
`

**Comment by timstall** [comment]
@BigShoots - with 0.2.9, is this still an issue?

**Comment by JoshRack** [comment]
Code has changed and is no longer relevant
