### ISSUE TITLE
[NodeCore 0.2.6] "Add block" messages not working as intended?

### ISSUE THREAD

**Issue by a123b** [VeriBlock/nodecore-releases#70]
My understanding is that the "add block" messages mentioned in the log file are created by nodes that just found a block and propagated across the network, so that every node that is synced can immediately add the new block. If this is not the case, this report is probably invalid.

If what I wrote above is true, every node should forward every "add block" messages to all connected peers the first time it receives it. Consequently, an incoming "add block" message burst would be expected with messages from different peers all referencing the same block.

What actually happens: "Add block" messages only come from one peer at a time, and sometimes there are multiple messages in very quick succession referencing consecutive blocks.

Maybe nodecore only forwards the "add block" message to its peers if they extend the local blockchain. A new block would only get propagated to connected peers then, peers in other peer groups would only see the new block after the sync mechanism kicks in at some later point and the other peers would mine a fork until this happens.

Again, I might misinterpret the purpose of the "add block" messages, but if I don't, this might be causing the fork explosion happening on the testnet lately.

**Comment by JoshRack** [comment]
No longer the same message flow in v0.3.x
