### ISSUE TITLE
[Feature Request][PoP Miner] Add Bitcoin wallet recovery options

### ISSUE THREAD

**Issue by a123b** [VeriBlock/nodecore-releases#73]
It might happen that the wallet file gets corrupted, especially the transaction/utxo cache. (e.g. #72)
This makes the wallet unusable even though the keys or the seed are intact.

Please implement the following features to mitigate corruptions like this:
- Add a possibility to clear and rebuild the transaction cache (without having to load the wallet)
- Wallet recovery using seed (the file contains 12 words, I assume it could be recovered with them)

**Comment by JoshRack** [comment]
Included since v0.3.0
