### ISSUE TITLE
pop miner don't output bitcoin transaction confirmation

### ISSUE THREAD

**Issue by Codefordl** [VeriBlock/nodecore-releases#77]
MINER: (2018-07-30 15:35:45) [87a737c5] Mining operation current action: Proving transaction included in Bitcoin block
  MINER: (2018-07-30 15:35:45) [92a19c8c] Mining operation current action: Proving transaction included in Bitcoin block
  MINER: (2018-07-30 15:35:45) [92a19c8c] Found transaction in Bitcoin block with header: 0000002077C52287DD4C0069F07D9F4156BF355BCB5CE5C39FB9D01B0F382AB100000000089CB47D192E4BE6D24C2F512DEAD7933D41B044104CB25F6E7380BB25FAE377CCBF5E5BFFFF001DD7601F73
  MINER: (2018-07-30 15:35:45) [e60d29d3] Found transaction in Bitcoin block with header: 0000002077C52287DD4C0069F07D9F4156BF355BCB5CE5C39FB9D01B0F382AB100000000089CB47D192E4BE6D24C2F512DEAD7933D41B044104CB25F6E7380BB25FAE377CCBF5E5BFFFF001DD7601F73
  MINER: (2018-07-30 15:35:45) [e60d29d3] Mining operation current action: Proving transaction included in Bitcoin block
  MINER: (2018-07-30 15:36:00) [0d2adbed] Mining operation current action: Ready
  MINER: (2018-07-30 15:36:00) [0d2adbed] Mining operation is now: RUNNING
  MINER: (2018-07-30 15:36:00) [0d2adbed] Mining operation current action: Getting PoP publication data
  MINER: (2018-07-30 15:36:00) [0d2adbed] Received PoP mining instructions, securing block: 0000000001497BB5B0E2F3FF0203178F6EB89B87D4A8EF8A
  MINER: (2018-07-30 15:36:00) [0d2adbed] Using miner address: VBamo4pXM3BY2oyvLMtx5MtPUAdFqv
  MINER: (2018-07-30 15:36:00) [0d2adbed] Mining operation current action: Creating Bitcoin transaction containing PoP publication data
   INFO: (2018-07-30 15:36:05) Received pending tx 'd43f7216a199f1973d27953cee20940e7bf64885696f3be74f7fcef817ddaea4', pending balance: '1.8526418 BTC'
  MINER: (2018-07-30 15:36:05) [0d2adbed] Signed Bitcoin transaction: 0100000001F49B8FB2D772FA1AF4D7ABAAEFBBD3E7712854FFDF2C62566AF5C5CC1EDC9B3B010000006A473044022037F9059E8A3F41BEF8FB096B5F4CA1334B6DEB2049652E753E486C180E8EB28D02200E0B750930E21D5903490BCE91B1CA7245B482DB0C1EEE9422777340F36CBA9801210284408B356C85CBADB71356AFED6E6D3F80BA7D401B2FAEA714D7AD031A151DE3FFFFFFFF020000000000000000536A4C500000B99200016938E316E10294024B8AD1F1DAEC8676532FA2543CE8FF163F67841BF1BACB8CE11A388C21348D6A4CBE1AF2F71C5B5EBF7B057DFF98E3F1D1A0AC17DEAB60AE823EFF83D6A2E742F9DB34E80A0B000000001976A9147EEDE78AFD6D8532D1D42DCDC78EB31C748C3CA888AC00000000
  MINER: (2018-07-30 15:36:05) [0d2adbed] Submitted Bitcoin transaction: d43f7216a199f1973d27953cee20940e7bf64885696f3be74f7fcef817ddaea4
  MINER: (2018-07-30 15:36:05) [0d2adbed] Mining operation current action: Waiting for transaction to be included in Bitcoin block
  ERROR: (2018-07-30 15:36:30) [0ed7b1aa] A running action was interrupted. Operation can be resubmitted.
  ERROR: (2018-07-30 15:36:30) [e60d29d3] A running action was interrupted. Operation can be resubmitted.

**Comment by JoshRack** [comment]
Many steps have been taken to address "stuck" or errored transactions. If similar behavior arises again, please open a new issue.
