### ISSUE TITLE
[Feature] Verbose option logging (info/medium/crit)

### ISSUE THREAD

**Issue by gsxryan** [VeriBlock/nodecore-releases#81]
Is there any option to specify level of logging?  

Should have levels of verbose such as informational, medium or higher, or only critical.  Logging seems to have a high IO rate for nodecore.

**Comment by timstall** [comment]
Yes: https://wiki.veriblock.org/index.php?title=HowTo_run_NodeCore#How_to_set_NodeCore_log_level
