### ISSUE TITLE
NODECORE STOP

### ISSUE THREAD

**Issue by q3579338** [VeriBlock/nodecore-releases#83]
Exception in thread "grpc-default-executor-3728" 04:52:39.164 [grpc-default-executor-3696] INFO  nodecore.f.b - Proof of Proof requested for latest block!
java.lang.OutOfMemoryError: Java heap space#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000005b705148, pid=12628, tid=0x0000000000005998
#
# JRE version: Java(TM) SE Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.181-b13 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0x115148]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\veriblock-nodecore-all-0.2.7\nodecore-0.2.7\bin\hs_err_pid12628.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Application terminated unexpectedly, press any key to exit

E3/WIN10/16G

**Comment by timstall** [comment]
@q3579338 with 0.2.9, is this still an issue?

**Comment by JoshRack** [comment]
Closing as the faulting code is no longer in NodeCore
