### ISSUE TITLE
[PoP Miner] State is only saved on "quit" command

### ISSUE THREAD

**Issue by a123b** [VeriBlock/nodecore-releases#84]
My PoP miner ran out of memory and hadn't executed any command in over 30 minutes, so I couldn't stop it using the `quit` command. Before I decided if i want to kill the process, I wanted to see how much I would lose, so I looked at the last modify time of the `pop.state` file and was surprised it wasn't changed since I started the miner. Guess I lost the rewards of the last 20 bitcoin blocks when the miner was still running :(

Please change the state saving behaviour to either save as soon as the state changes or periodically (once every minute? or make this configurable?) to prevent reward loss in case of a crash.

**Comment by a123b** [comment]
The worst thing about this is that it doesn't even save the state on Ctrl+C. I have lost rewards twice now because I accidentally hit Ctrl+C.

**Comment by JoshRack** [comment]
This has been changed so that each operation is saved independently whenever its state changes.
