### ISSUE TITLE
POP rewards showing on block explorer but not in balance on synced node.

### ISSUE THREAD

**Issue by BigShoots** [VeriBlock/nodecore-releases#85]
When I check my balance on the block explorer I have 10k more coins than I do in my balance when I check on a synced node.

This is the wallet I use for POP mining so I assume my POP rewards are not being reflected properly.

**Comment by JoshRack** [comment]
NodeCore is considered the source of truth. The block explorer has been revamped considerably to more consistently and reliably reflect NodeCore's state.
