### ISSUE TITLE
[Nodecore Pool] stoppool command doesn't always stop the pool thread completely

### ISSUE THREAD

**Issue by a123b** [VeriBlock/nodecore-releases#90]
After restarting the pool by executing `stoppool` and `startpool` in very quick succession from time to time, I noticed something strange going on with the `poolshares-solo.txt` file: There were multiple versions of it being "competitively" saved to the disk, so the file was modified multiple times per second, jumping back and forth between multiple "forks" of the file (rounds/shares disappearing and appearing again).

Then I noticed in the nodecore log that messages like `Finished writing mining job...` appeard multiple times within the same timestamp (same millisecond).

It seems like `stoppool` sometimes only closes the pool thread's sockets but leaves the thread itself running, maybe if a `startpool` command is executed too soon after the stop command?

**Comment by JoshRack** [comment]
Much of the pool code has changed including no longer using the txt files.
