### ISSUE TITLE
Start sync from partial fails

### ISSUE THREAD

**Issue by nickoarg** [VeriBlock/nodecore-releases#98]
So I was trying to create a node yesterday on an 8gb machine, withouth the Xmx1024 flag. It crashed. Then I've added that flag and restarted the node without erasing the testnet folder. Crashed again. Added swap partition of additional 8gb. Crashed again. Upgraded to 32Gb of ram. Crashed again, always with the same memory error and memory usage always going up constantly for the java process.
Deleted the testnet folder, and now the sync process is just using 5% mem. Hope this is the one
![image](https://user-images.githubusercontent.com/22946592/43933657-4c49bd50-9c21-11e8-8df3-afd10b1cdc00.png)

**Comment by Hou5e** [comment]
It looks like most of these issues come from the default option of 8GB set in the 'nodecore.bat' (Windows), 'nodecore' (Linux) not being sufficient to reload the blockchain.

It is mentioned here: https://wiki.veriblock.org/index.php?title=HowTo_run_NodeCore#Java_out-of-memory
But, the example doesn't give new users the answer of needing to change it to like:
16GB RAM PC:  set DEFAULT_JVM_OPTS="-Xmx**15g**"
or for 32GB RAM PC:  set DEFAULT_JVM_OPTS="-Xmx**25g**"

It would be nice if the developers would change the default option to a value that will work. And, ideally work out a solution to not need that much RAM.

It sounds like running the latest Java 10 might help over running Java 8. I haven't tried it yet.

**Comment by JoshRack** [comment]
Closing as much has been done to address memory pressure since this was created.
